import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const sourceSchema = z.object({
  label: z.string().min(1),
  url: z.string().url(),
  type: z.enum(['媒体', '官方', '视频']),
});

const refSchema = z.object({
  label: z.string().min(1),
  url: z.string().url(),
  type: z.enum(['媒体', '官方', '视频']).optional(),
});

export const eventsSchema = z.object({
  // Note: entry.id is auto-generated by the glob loader from the filename;
  // no frontmatter id field. Routes use entry.id.
  date: z.coerce.date(),
  category: z.enum(['判罚争议', '裁判执法', 'FIFA治理', '种族歧视指控', '其他']),
  status: z.enum(['报道争议', '已被质疑', '官方裁定']).default('报道争议'),
  title_zh: z.string().min(1),
  title_en: z.string().min(1),
  summary_zh: z.string().min(1),
  summary_en: z.string().min(1),
  tags: z.array(z.string()).default([]),
  sources: z.array(sourceSchema).min(1),
  response: z
    .object({ who: z.string(), text_zh: z.string().optional(), text_en: z.string().optional(), source: refSchema })
    .optional(),
  ruling: z
    .object({ verdict_zh: z.string(), verdict_en: z.string().optional(), source: refSchema })
    .optional(),
});

const events = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/data/events' }),
  schema: eventsSchema,
});

export const collections = { events };
